services:
  - type: web
    name: union-app
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node $PWD/server/dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false