services:
  - type: web
    name: union-app
    runtime: node
    buildCommand: npm ci && npm run build && ls -la server/dist
    startCommand: pwd && ls -la && node server/dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false